require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WhosController do

  def mock_who(stubs={})
    @mock_who ||= mock_model(Who, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all whos as @whos" do
      Who.stub(:all) { [mock_who] }
      get :index
      assigns(:whos).should eq([mock_who])
    end
  end

  describe "GET show" do
    it "assigns the requested who as @who" do
      Who.stub(:find).with("37") { mock_who }
      get :show, :id => "37"
      assigns(:who).should be(mock_who)
    end
  end

  describe "GET new" do
    it "assigns a new who as @who" do
      Who.stub(:new) { mock_who }
      get :new
      assigns(:who).should be(mock_who)
    end
  end

  describe "GET edit" do
    it "assigns the requested who as @who" do
      Who.stub(:find).with("37") { mock_who }
      get :edit, :id => "37"
      assigns(:who).should be(mock_who)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created who as @who" do
        Who.stub(:new).with({'these' => 'params'}) { mock_who(:save => true) }
        post :create, :who => {'these' => 'params'}
        assigns(:who).should be(mock_who)
      end

      it "redirects to the created who" do
        Who.stub(:new) { mock_who(:save => true) }
        post :create, :who => {}
        response.should redirect_to(who_url(mock_who))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved who as @who" do
        Who.stub(:new).with({'these' => 'params'}) { mock_who(:save => false) }
        post :create, :who => {'these' => 'params'}
        assigns(:who).should be(mock_who)
      end

      it "re-renders the 'new' template" do
        Who.stub(:new) { mock_who(:save => false) }
        post :create, :who => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested who" do
        Who.stub(:find).with("37") { mock_who }
        mock_who.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :who => {'these' => 'params'}
      end

      it "assigns the requested who as @who" do
        Who.stub(:find) { mock_who(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:who).should be(mock_who)
      end

      it "redirects to the who" do
        Who.stub(:find) { mock_who(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(who_url(mock_who))
      end
    end

    describe "with invalid params" do
      it "assigns the who as @who" do
        Who.stub(:find) { mock_who(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:who).should be(mock_who)
      end

      it "re-renders the 'edit' template" do
        Who.stub(:find) { mock_who(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested who" do
      Who.stub(:find).with("37") { mock_who }
      mock_who.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the whos list" do
      Who.stub(:find) { mock_who }
      delete :destroy, :id => "1"
      response.should redirect_to(whos_url)
    end
  end

end
